### ISSUE TITLE
DynamicSqlUtil 的bug

### ISSUE THREAD

**Issue by liubo777** [wiscess/wiscess#5]
while (m.find()) {
        	String name = m.group(3);
        	String preValue = m.group(2);
        	String lastValue = m.group(4);

>         	paramsMap.put(name, preValue+params.get(name)+lastValue);  //这段代码有问题。

        	//paramValuesList.add(params.get(name));
        	paramNamesList.add(name);
        }

这个preValue和lastValue看代码想做模糊匹配时匹配%用的，但是当params.get(name)返回null时，通过和preValue和lastValue直接相+  就变成"null"字符串了。
这样，当使用ArgumentPreparedStatementSetter 快速设置参数时，它的判断方式是
if (inValueToUse == null) {
            setNull(ps, paramIndex, sqlTypeToUse, typeNameToUse);
        } else {
            setValue(ps, paramIndex, sqlTypeToUse, typeNameToUse, scale, inValueToUse);
        }
inValueToUse并不能识别 “null” 这种字符串，假如，这个参数赋给一个非varchar类型的列，就会导致sql异常。

**Comment by wanghai114** [comment]
这个情况，先不考虑paramsMap中存放的name是null或“null”或“%null%”，先看后面代码
sql = sql.replaceAll(strPattern, "?");
这句会将sql语句变成 ...and name=?...的形式，在设置参数时，这个?必须要给一个值，可能是null或"null"，所以执行语句的意义为：查询name值为null的数据集，与传入空值的初衷不一样，所以应该从sql语句的写法来进行判断，如下：
<#if name?has_content>
  and name like %:name%
</#if>
这样，传入name，代表查询name值为传入值的模糊匹配，不传name时，代表不加name的限制条件，基于这种处理方式，params.get(name)的值必然是有数据的，不应该会出现null的情况。
如果想查询name值为空的数据，可以通过指定name的特殊内容来进行判断，如：
name=-1代表查询name为空的数据；
<#if name?has_content>
  <#if name==-1>
    and isnull(name,'')=''
  <#else>
    and name like %:name%
  </#if>
</#if>
